from openai import OpenAI

client = OpenAI(api_key="YOUR_API_KEY")

# We will use the SAME model for all requests
model = "gpt-4.1-mini"


# Different prompts
prompts = [
    "Explain Python.",

    "Explain Python to a beginner.",

    """
    Explain Python to a beginner.

    Give one real-world example.
    Keep the answer under 3 sentences.
    """
]


# Send each prompt to the SAME model
for prompt in prompts:

    response = client.responses.create(
        model=model,
        input=prompt
    )

    print("=" * 60)

    # Show the prompt we sent
    print("PROMPT:")
    print(prompt)

    # Show the response generated by the model
    print("\nRESPONSE:")
    print(response.output_text)